sueyoshi_practice10_04_submit
ddt-sueyoshi/meikaiJava pull request #17
Opened 2022-06-08 12:30 UTC by ddt-sueyoshi

演習10−4の実装が完了しましたのでレビューをお願いします。

/**
 * 
 *  演習10−4 日付クラス第４版（p.346）を以下のように改良せよ。
 *         ・引数を受け取らないコンストラクタによるインスタンスの生成時は、西暦１年１月１日で初期化するのではなく、プログラム実行時の日付で初期化する。
 *         ・引数を受け取るコンストラクタに不正な値が指定された場合は、適当な値に調整する
 *         （例えば13月が指定された場合は１２月とする／9月31日と指定された場合は9月30日とする）。
 * 
 *         さらに以下に示すメソッドを追加すること： 年内での経過日数（その年の元旦から数えて何日目であるか）を求めるメソッド、
 *         年内の残り日数を求めるメソッド、 他の日付との前後関係（より前の日付か／同じ日付か／より後の日付か）を判定するインスタンスメソッド、
 *         二つの日付の前後関係を判定するクラスメソッド、
 *         日付を一つ後ろに進めるメソッド（日付が2012年12月31日であれば、2013年1月1日に更新する）、 次の日の日付を返却するメソッド、
 *         日付を一つ前に戻すメソッド、 前の日の日付を返却するメソッド、 日付をn日後ろに進めるメソッド、 n日後の日付を返却するメソッド、
 *         日付をn日前に戻すメソッド、 n日前の日付返却するメソッド etc...
 */

2022-06-15 12:43 UTC, ddt-mentor requested changes

2022-07-06 11:44 UTC, ddt-sueyoshi commented on meikaiJava/src/chapter10/practice10_04.java
> +		System.out.println("　今日の日付：" + today.getYear() + "年" + today.getMonth() + "月" + today.getDay() + "日");
GregorianCalendar.MONTH の使用の問題でしたので調節しました。
https://github.com/ddt-sueyoshi/meikaiJava/pull/17/commits/c53bae3e0bdf05e78198258ea8ff6b38ec7d111d#diff-d73005d644c42125ae68198d8119ce89343acda74a8aead099d53f1b57ee364aR27

2022-07-06 11:50 UTC, ddt-sueyoshi commented on meikaiJava/src/chapter10/practice10_04.java
> +			System.out.println("　日付：" + day.getYear() + "年" + day.getMonth() + "月" + day.getDay() + "日");
パラメータがない部分はプログラム実行日と同じになるように調整しました。
またその影響でバリデーションを追加しました。
https://github.com/ddt-sueyoshi/meikaiJava/pull/17/commits/9b27775818b87b7a2015992a3db130d585c1722f

2022-07-06 11:51 UTC, ddt-sueyoshi commented on meikaiJava/src/chapter10/practice10_04.java
> +		while (countdownDays() < n) {
各メソッド内にコメントを追加しました。
https://github.com/ddt-sueyoshi/meikaiJava/pull/17#:~:text=sueyoshi_fix%20for%20review-,c53bae3,-sueyoshi_add%20validation

2022-07-06 12:19 UTC, merged